In [2]:
import pandas as pd 

data=pd.read_csv('Iris.csv')
data.head()
print(data.info())  # Get an overview of data types and missing values
print(data.describe())  # Summary statistics

print(data['Species'].unique())  # Should return ['setosa' 'versicolor' 'virginica']

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB
None
               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000    

In [3]:
#Check for missing values
print(data.isnull().sum())

# Encode categorical variables
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['Species'] = le.fit_transform(data['Species'])  # Now it should be [0, 1, 2]

# Verify Encoding
print(data['Species'].unique())

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64
[0 1 2]


In [4]:
from sklearn.model_selection import train_test_split

x= data.drop(columns=['Species']).values
y = data['Species'].values


x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42,stratify=y)

In [5]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=100, max_depth=5,random_state=42)

model.fit(x_train, y_train)

train_acc = model.score(x_train, y_train)
test_acc = model.score(x_test, y_test)
print(f'Training Accuracy: {train_acc:.2f}')
print(f'Test Accuracy: {test_acc:.2f}')

Training Accuracy: 1.00
Test Accuracy: 1.00


In [6]:
from sklearn.metrics import  accuracy_score

y_pred = model.predict(x_test)

accuracy=accuracy_score(y_test, y_pred)
print(accuracy)

1.0


In [7]:
print(f"Model Accuracy: {accuracy * 100:.2f}%")

Model Accuracy: 100.00%


In [8]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(model, x, y, cv=5)  # 5-fold cross-validation
print(f"Cross-validation accuracy: {scores.mean() * 100:.2f}%")


Cross-validation accuracy: 94.67%


In [9]:
from sklearn.neighbors import KNeighborsClassifier

knn=KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train,y_train)

accuracy_knn=knn.score(x_test,y_test)
print(f"KNN Accuracy: {accuracy_knn*100:.2f}%")

KNN Accuracy: 100.00%


In [10]:
from sklearn.svm import SVC

svm=SVC(kernel="rbf")
svm.fit(x_train,y_train)

accuracy_svm=svm.score(x_test,y_test)
print(f"SVM Accuracy: {accuracy_svm}")

SVM Accuracy: 1.0


In [11]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression(max_iter=200)
log_reg.fit(x_train, y_train)

accuracy_log_reg = log_reg.score(x_test, y_test)
print(f"Logistic Regression Accuracy: {accuracy_log_reg * 100:.2f}%")


Logistic Regression Accuracy: 100.00%


/home/sfm/.local/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [12]:
import numpy as np

# Check original dataset class distribution
print("Original class distribution:")
print(data['Species'].value_counts())

# Check training dataset class distribution
print("\nTraining set distribution:")
print(np.bincount(y_train))

# Check testing dataset class distribution
print("\nTesting set distribution:")
print(np.bincount(y_test))


Original class distribution:
Species
0    50
1    50
2    50
Name: count, dtype: int64

Training set distribution:
[35 35 35]

Testing set distribution:
[15 15 15]


In [13]:
# KNN
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train, y_train)
print(f"KNN Accuracy: {knn.score(x_test, y_test) * 100:.2f}%")

# SVM
from sklearn.svm import SVC
svm = SVC(kernel="rbf")
svm.fit(x_train, y_train)
print(f"SVM Accuracy: {svm.score(x_test, y_test) * 100:.2f}%")

# Logistic Regression
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression(max_iter=500)
log_reg.fit(x_train, y_train)
print(f"Logistic Regression Accuracy: {log_reg.score(x_test, y_test) * 100:.2f}%")


KNN Accuracy: 100.00%
SVM Accuracy: 100.00%


Logistic Regression Accuracy: 100.00%


/home/sfm/.local/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [14]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

log_reg = LogisticRegression(max_iter=500)
log_reg.fit(x_train_scaled, y_train)

print(f"Logistic Regression Accuracy (with scaling): {log_reg.score(x_test_scaled, y_test) * 100:.2f}%")


Logistic Regression Accuracy (with scaling): 97.78%


In [15]:
print(f"Random Forest Accuracy: {accuracy * 100:.2f}%")
print(f"Cross-validation accuracy: {scores.mean() * 100:.2f}%")
print(f"KNN Accuracy: {accuracy_knn*100:.2f}%")
print(f"SVM Accuracy: {accuracy_svm*100:.2f}%")
print(f"Logistic Regression Accuracy: {accuracy_log_reg * 100:.2f}%")
print(f"Logistic Regression Accuracy (with scaling): {log_reg.score(x_test_scaled, y_test) * 100:.2f}%")

Random Forest Accuracy: 100.00%
Cross-validation accuracy: 94.67%
KNN Accuracy: 100.00%
SVM Accuracy: 100.00%
Logistic Regression Accuracy: 100.00%
Logistic Regression Accuracy (with scaling): 97.78%
